name: Firebase UI Tests
on:
  pull_request:
    branches:
      - main
      - develop
      
jobs:
  setup-flank:
    name: Run Firebase UI Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11
          cache: 'gradle'
      - name: Build Test APK
        run: ./gradlew assembleDebug && ./gradlew assembleDebugAndroidTest
      - uses: Flank/flank@master
        with: 
          service_account: ${{ secrets.GOOGLE_CREDENTIALS }}
          platform: android
          flank_configuration_file: flank.yml
